#!/usr/bin/env node

const fs = require('fs');
const showdown  = require('showdown');

const converter = new showdown.Converter();
const template = fs.readFileSync('template.html').toString();

fs.writeFile(
  'index.html',
  template.replace(
    /<(markdown)\s*\/?>(?:<\/\1>)?/,
    converter.makeHtml(
      fs.readFileSync('README.md').toString()
    )
  ),
  error => {
    if (error)
      console.error(error);
  }
);
